# Generated by Django 5.2.6 on 2025-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Oblige l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
    ]
