# Generated by Django 5.2.6 on 2025-10-09 13:06

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_arrondissement', models.CharField(help_text="Code INSEE de l'arrondissement", max_length=10, unique=True, verbose_name="Code d'arrondissement")),
                ('nom_arrondissement', models.CharField(db_index=True, max_length=200, verbose_name="Nom de l'arrondissement")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'db_table': 'arrondissements',
                'ordering': ['nom_arrondissement'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=2154, verbose_name='Géométrie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la couche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('LineString', 'Ligne'), ('Polygon', 'Polygone'), ('MultiPoint', 'Multi-points'), ('MultiLineString', 'Multi-lignes'), ('MultiPolygon', 'Multi-polygones')], max_length=50, verbose_name='Type de géométrie')),
                ('identifier_field', models.CharField(default='id', max_length=100, verbose_name='Champ identifiant')),
                ('style_color', models.CharField(default='#3388ff', max_length=7, verbose_name='Couleur')),
                ('style_weight', models.IntegerField(default=2, verbose_name='Épaisseur du trait')),
                ('style_opacity', models.FloatField(default=0.8, verbose_name='Opacité')),
                ('style_fill_opacity', models.FloatField(default=0.2, verbose_name='Opacité du remplissage')),
                ('source_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fichier source')),
                ('srid', models.IntegerField(default=2154, verbose_name='SRID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible par défaut')),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_canton', models.CharField(help_text='Code INSEE du canton', max_length=10, unique=True, verbose_name='Code de canton')),
                ('nom_canton', models.CharField(db_index=True, max_length=200, verbose_name='Nom du canton')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cantons', to='observatoire.arrondissement', verbose_name='Arrondissement')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canton', to='observatoire.feature', verbose_name='Entité géographique associée')),
            ],
            options={
                'verbose_name': 'Canton',
                'verbose_name_plural': 'Cantons',
                'db_table': 'cantons',
                'ordering': ['nom_canton'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_insee', models.CharField(help_text='Code INSEE à 5 chiffres de la commune', max_length=5, unique=True, verbose_name='Code INSEE')),
                ('nom', models.CharField(db_index=True, max_length=200, verbose_name='Nom de la commune')),
                ('zone_emploi', models.CharField(blank=True, max_length=200, null=True, verbose_name="Zone d'emploi")),
                ('type_doc_urba_approuve', models.CharField(blank=True, choices=[('PLU', "Plan Local d'Urbanisme"), ('POS', "Plan d'Occupation des Sols"), ('CC', 'Carte Communale'), ('RNU', "Règlement National d'Urbanisme"), ('AUCUN', 'Aucun document')], max_length=10, null=True, verbose_name="Type de document d'urbanisme approuvé")),
                ('date_doc_urba_approuve', models.DateField(blank=True, null=True, verbose_name="Date du document d'urbanisme approuvé")),
                ('type_doc_urba_en_cours', models.CharField(blank=True, choices=[('PLU', "Plan Local d'Urbanisme"), ('POS', "Plan d'Occupation des Sols"), ('CC', 'Carte Communale'), ('RNU', "Règlement National d'Urbanisme"), ('AUCUN', 'Aucun document')], max_length=10, null=True, verbose_name="Type de document d'urbanisme en cours")),
                ('commentaires_generaux_urba_previs', models.TextField(blank=True, null=True, verbose_name='Commentaires généraux urbanisme prévisionnel')),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Superficie (km²)')),
                ('population', models.PositiveIntegerField(blank=True, help_text='Population municipale', null=True, verbose_name='Population')),
                ('nom_mairie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la mairie')),
                ('adresse_mairie', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse de la mairie')),
                ('code_postal_commune', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal de la commune')),
                ('telephone_mairie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de la mairie')),
                ('fax_mairie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax de la mairie')),
                ('email_mairie', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email de la mairie')),
                ('mobile_mairie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile de la mairie')),
                ('horaires_mairie', models.TextField(blank=True, null=True, verbose_name='Horaires de la mairie')),
                ('commentaires_generaux_commune', models.TextField(blank=True, null=True, verbose_name='Commentaires généraux sur la commune')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='observatoire.arrondissement', verbose_name='Arrondissement')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='observatoire.canton', verbose_name='Canton')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commune', to='observatoire.feature', verbose_name='Entité géographique associée')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'communes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissement', to='observatoire.feature', verbose_name='Entité géographique associée'),
        ),
        migrations.AddField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='observatoire.layer', verbose_name='Couche'),
        ),
        migrations.CreateModel(
            name='UGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_uge', models.CharField(help_text="Identifiant unique de l'UGE", max_length=50, unique=True, verbose_name='Code UGE')),
                ('nom_uge', models.CharField(db_index=True, max_length=200, verbose_name="Nom de l'UGE")),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200, null=True, verbose_name="Maître d'ouvrage")),
                ('type_competence', models.CharField(blank=True, choices=[('PRODUCTION', "Production d'eau potable"), ('DISTRIBUTION', "Distribution d'eau potable"), ('ASSAINISSEMENT', 'Assainissement'), ('GESTION', 'Gestion globale')], max_length=20, null=True, verbose_name='Type de compétence')),
                ('type_mode_exploitation', models.CharField(blank=True, choices=[('REGIE', 'Régie directe'), ('DSP', 'Délégation de Service Public'), ('CONCESSION', 'Concession'), ('AFF_TERME', 'Affermage'), ('MIXTE', 'Mode mixte')], max_length=20, null=True, verbose_name="Type de mode d'exploitation")),
                ('exploitant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Exploitant')),
                ('date_fin_contrat_dsp_concession', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat DSP/concession')),
                ('prestation_service', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prestation de service')),
                ('nature_prestation_service', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nature de la prestation de service')),
                ('date_fin_contrat_prestation_service', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat de prestation de service')),
                ('zone_homogene', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zone homogène')),
                ('date_debut_validite_uge', models.DateField(blank=True, null=True, verbose_name="Date de début de validité de l'UGE")),
                ('date_fin_validite_uge', models.DateField(blank=True, null=True, verbose_name="Date de fin de validité de l'UGE")),
                ('reglement_service', models.TextField(blank=True, null=True, verbose_name='Règlement de service')),
                ('plan_secours_aep', models.TextField(blank=True, null=True, verbose_name='Plan de secours AEP')),
                ('date_plan_secours_aep', models.DateField(blank=True, null=True, verbose_name='Date du plan de secours AEP')),
                ('comment_generaux_uge', models.TextField(blank=True, null=True, verbose_name="Commentaires généraux sur l'UGE")),
                ('comment_princip_fonctionnement', models.TextField(blank=True, null=True, verbose_name='Commentaire principal de fonctionnement')),
                ('comment_difficulte_exploitation', models.TextField(blank=True, null=True, verbose_name="Commentaire sur les difficultés d'exploitation")),
                ('comment_difficulte_satisf_besoins', models.TextField(blank=True, null=True, verbose_name='Commentaire sur les difficultés à satisfaire les besoins')),
                ('comment_conflit_usage_ressource', models.TextField(blank=True, null=True, verbose_name="Commentaire sur les conflits d'usage de la ressource")),
                ('comment_retour_exp_crises', models.TextField(blank=True, null=True, verbose_name="Commentaire sur le retour d'expérience des crises")),
                ('comment_proj_souhait_uge', models.TextField(blank=True, null=True, verbose_name="Commentaire sur les projets souhaités pour l'UGE")),
                ('comment_politique_tarification', models.TextField(blank=True, null=True, verbose_name='Commentaire sur la politique de tarification')),
                ('comment_politique_economies_eau', models.TextField(blank=True, null=True, verbose_name="Commentaire sur la politique d'économies d'eau")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uge', to='observatoire.feature', verbose_name='Entité géographique associée')),
            ],
            options={
                'verbose_name': "Unité de Gestion d'Eau (UGE)",
                'verbose_name_plural': "Unités de Gestion d'Eau (UGE)",
                'db_table': 'uges',
                'ordering': ['nom_uge'],
            },
        ),
        migrations.CreateModel(
            name='UDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ins_udi', models.CharField(help_text="Identifiant INS unique de l'UDI", max_length=50, unique=True, verbose_name='Code INS UDI')),
                ('nom_ins_udi', models.CharField(db_index=True, max_length=200, verbose_name='Nom INS UDI')),
                ('date_debut_validite_udi', models.DateField(blank=True, null=True, verbose_name="Date de début de validité de l'UDI")),
                ('date_fin_validite_udi', models.DateField(blank=True, null=True, verbose_name="Date de fin de validité de l'UDI")),
                ('type_usage_direct', models.CharField(blank=True, choices=[('AEP', 'Alimentation en Eau Potable'), ('INDUSTRIEL', 'Usage industriel'), ('AGRICOLE', 'Usage agricole'), ('MIXTE', 'Usage mixte')], max_length=20, null=True, verbose_name="Type d'usage direct")),
                ('type_etat_activite_ins', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_CONSTRUCTION', 'En construction'), ('EN_DEMOLITION', 'En démolition'), ('PROJET', 'Projet')], max_length=20, null=True, verbose_name="Type/État d'activité INS")),
                ('type_nature_eau', models.CharField(blank=True, choices=[('EAU_BRUTE', 'Eau brute'), ('EAU_TRAITEE', 'Eau traitée'), ('EAU_POTABLE', 'Eau potable'), ('EAU_DISTRIBUTEE', 'Eau distribuée')], max_length=20, null=True, verbose_name="Type/Nature de l'eau")),
                ('comment_udi', models.TextField(blank=True, null=True, verbose_name="Commentaires sur l'UDI")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='udi', to='observatoire.feature', verbose_name='Entité géographique associée')),
                ('uge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udis', to='observatoire.uge', verbose_name='UGE associée')),
            ],
            options={
                'verbose_name': "Unité de Distribution d'Eau (UDI)",
                'verbose_name_plural': "Unités de Distribution d'Eau (UDI)",
                'db_table': 'udis',
                'ordering': ['nom_ins_udi'],
            },
        ),
        migrations.CreateModel(
            name='Captage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ins_captage', models.CharField(help_text='Identifiant INS unique du captage', max_length=50, unique=True, verbose_name='Code INS captage')),
                ('nom_captage', models.CharField(db_index=True, max_length=200, verbose_name='Nom du captage')),
                ('code_bss', models.CharField(blank=True, help_text='Code Banque du Sous-Sol', max_length=50, null=True, verbose_name='Code BSS')),
                ('code_prelev_ae', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code prélèvement A/E')),
                ('autre_libelle_captage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre libellé du captage')),
                ('date_debut_validite_captage', models.DateField(blank=True, null=True, verbose_name='Date de début de validité du captage')),
                ('date_fin_validite_captage', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité du captage')),
                ('type_usage_direct', models.CharField(blank=True, choices=[('AEP', 'Alimentation en Eau Potable'), ('INDUSTRIEL', 'Usage industriel'), ('AGRICOLE', 'Usage agricole'), ('MIXTE', 'Usage mixte')], max_length=20, null=True, verbose_name="Type d'usage direct")),
                ('type_etat_activite_ins', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_CONSTRUCTION', 'En construction'), ('EN_DEMOLITION', 'En démolition'), ('PROJET', 'Projet')], max_length=20, null=True, verbose_name="Type/État d'activité INS")),
                ('code_utilisation_ouvrage', models.CharField(blank=True, max_length=200, null=True, verbose_name="Utilisation de l'ouvrage")),
                ('type_nature_eau', models.CharField(blank=True, choices=[('EAU_BRUTE', 'Eau brute'), ('EAU_TRAITEE', 'Eau traitée'), ('EAU_POTABLE', 'Eau potable')], max_length=20, null=True, verbose_name="Type/Nature de l'eau")),
                ('type_captage', models.CharField(blank=True, choices=[('FORAGE', 'Forage'), ('PUITS', 'Puits'), ('SOURCE', 'Source'), ('DRAINAGE', 'Drainage'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='Type de captage')),
                ('altitude_m_ngf', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude en mètres Nivellement Général de la France', max_digits=8, null=True, verbose_name='Altitude (m NGF)')),
                ('description_ouvrage', models.TextField(blank=True, null=True, verbose_name="Description de l'ouvrage")),
                ('type_etat_proced_protection', models.CharField(blank=True, choices=[('EN_COURS', 'En cours'), ('APPROUVEE', 'Approuvée'), ('ABANDONNEE', 'Abandonnée'), ('AUCUNE', 'Aucune')], max_length=20, null=True, verbose_name='Type/État de procédure de protection')),
                ('date_rapport_hydro', models.DateField(blank=True, null=True, verbose_name='Date du rapport hydrogéologique')),
                ('date_delib_proc_protection', models.DateField(blank=True, null=True, verbose_name='Date de délibération de procédure de protection')),
                ('date_recevabilite_dup', models.DateField(blank=True, null=True, verbose_name='Date de recevabilité DUP')),
                ('date_dup', models.DateField(blank=True, null=True, verbose_name='Date de DUP')),
                ('q_dup_l_s', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité DUP (L/s)')),
                ('q_dup_m3_h', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité DUP (m³/h)')),
                ('q_dup_m3_j', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité DUP (m³/j)')),
                ('q_dup_m3_an', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantité DUP (m³/an)')),
                ('capa_prod_captage_m3_h', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Capacité de production du captage (m³/h)')),
                ('potentiel_prod_captage_m3_h', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potentiel de production du captage (m³/h)')),
                ('nb_pompes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pompes')),
                ('existence_telegestion', models.BooleanField(default=False, verbose_name='Existence de la télégestion')),
                ('existence_alarme_anti_intrusion', models.BooleanField(default=False, verbose_name="Existence d'alarme anti-intrusion")),
                ('existence_report_alarme', models.BooleanField(default=False, verbose_name="Existence de report d'alarme")),
                ('comment_status_ouvrage', models.TextField(blank=True, null=True, verbose_name="Commentaire sur le statut de l'ouvrage")),
                ('comment_environ_risques', models.TextField(blank=True, null=True, verbose_name="Commentaires sur l'environnement et les risques")),
                ('comment_problemes', models.TextField(blank=True, null=True, verbose_name='Commentaires sur les problèmes')),
                ('comment_generaux_captage', models.TextField(blank=True, null=True, verbose_name='Commentaires généraux sur le captage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commune_implantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captages', to='observatoire.commune', verbose_name="Commune d'implantation")),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captage', to='observatoire.feature', verbose_name='Entité géographique associée')),
                ('uge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captages', to='observatoire.uge', verbose_name='UGE associée')),
            ],
            options={
                'verbose_name': "Captage d'eau",
                'verbose_name_plural': "Captages d'eau",
                'db_table': 'captages',
                'ordering': ['nom_captage'],
            },
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['code_insee'], name='communes_code_in_0d681a_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['nom'], name='communes_nom_78712c_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['arrondissement'], name='communes_arrondi_1d00e5_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['canton'], name='communes_canton__310694_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['type_doc_urba_approuve'], name='communes_type_do_3de79f_idx'),
        ),
        migrations.AddIndex(
            model_name='canton',
            index=models.Index(fields=['code_canton'], name='cantons_code_ca_757b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='canton',
            index=models.Index(fields=['nom_canton'], name='cantons_nom_can_a388d2_idx'),
        ),
        migrations.AddIndex(
            model_name='canton',
            index=models.Index(fields=['arrondissement'], name='cantons_arrondi_5be527_idx'),
        ),
        migrations.AddIndex(
            model_name='arrondissement',
            index=models.Index(fields=['code_arrondissement'], name='arrondissem_code_ar_8e32ad_idx'),
        ),
        migrations.AddIndex(
            model_name='arrondissement',
            index=models.Index(fields=['nom_arrondissement'], name='arrondissem_nom_arr_4d5521_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['layer'], name='features_layer_i_335aee_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['code_uge'], name='uges_code_ug_6f5172_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['nom_uge'], name='uges_nom_uge_38eb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['type_competence'], name='uges_type_co_83f221_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['type_mode_exploitation'], name='uges_type_mo_54ee74_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['maitre_ouvrage'], name='uges_maitre__d96740_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['exploitant'], name='uges_exploit_e5e8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['date_debut_validite_uge'], name='uges_date_de_a1ab2f_idx'),
        ),
        migrations.AddIndex(
            model_name='uge',
            index=models.Index(fields=['date_fin_validite_uge'], name='uges_date_fi_704f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['code_ins_udi'], name='udis_code_in_aee2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['nom_ins_udi'], name='udis_nom_ins_f19818_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['uge'], name='udis_uge_id_6c0bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['type_usage_direct'], name='udis_type_us_82a1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['type_etat_activite_ins'], name='udis_type_et_8b3737_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['type_nature_eau'], name='udis_type_na_e7e7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['date_debut_validite_udi'], name='udis_date_de_f17b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='udi',
            index=models.Index(fields=['date_fin_validite_udi'], name='udis_date_fi_5f32b5_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['code_ins_captage'], name='captages_code_in_591a16_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['nom_captage'], name='captages_nom_cap_f8475f_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['uge'], name='captages_uge_id_d6c850_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['commune_implantation'], name='captages_commune_d69ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['type_usage_direct'], name='captages_type_us_0eb63c_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['type_etat_activite_ins'], name='captages_type_et_5fc257_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['type_captage'], name='captages_type_ca_f62c93_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['type_nature_eau'], name='captages_type_na_0b3228_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['date_debut_validite_captage'], name='captages_date_de_ebdf25_idx'),
        ),
        migrations.AddIndex(
            model_name='captage',
            index=models.Index(fields=['date_fin_validite_captage'], name='captages_date_fi_8a559d_idx'),
        ),
    ]
