# Generated by Django 5.2.6 on 2025-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udi',
            name='communes',
            field=models.ManyToManyField(related_name='udis', to='observatoire.commune', verbose_name="Communes desservies par l'UDI"),
        ),
        migrations.AddField(
            model_name='udi',
            name='nom_quartier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du quartier desservi'),
        ),
    ]
