# Generated by Django 5.2.6 on 2025-10-03 11:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la couche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('LineString', 'Ligne'), ('Polygon', 'Polygone'), ('MultiPoint', 'Multi-points'), ('MultiLineString', 'Multi-lignes'), ('MultiPolygon', 'Multi-polygones')], max_length=50, verbose_name='Type de géométrie')),
                ('identifier_field', models.CharField(default='id', max_length=100, verbose_name='Champ identifiant')),
                ('style_color', models.CharField(default='#3388ff', max_length=7, verbose_name='Couleur')),
                ('style_weight', models.IntegerField(default=2, verbose_name='Épaisseur du trait')),
                ('style_opacity', models.FloatField(default=0.8, verbose_name='Opacité')),
                ('style_fill_opacity', models.FloatField(default=0.2, verbose_name='Opacité du remplissage')),
                ('source_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fichier source')),
                ('srid', models.IntegerField(default=2154, verbose_name='SRID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible par défaut')),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=2154, verbose_name='Géométrie')),
                ('properties', models.JSONField(default=dict, verbose_name='Propriétés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='observatoire.layer', verbose_name='Couche')),
            ],
            options={
                'db_table': 'features',
                'indexes': [models.Index(fields=['layer'], name='features_layer_i_335aee_idx')],
            },
        ),
    ]
