# Generated by Django 5.2.6 on 2025-10-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0002_udi_communes_udi_nom_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udi',
            name='feature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='udi', to='observatoire.feature', verbose_name='Entité géographique associée'),
        ),
    ]
