# Generated by Django 5.2.6 on 2025-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0003_alter_udi_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udi',
            name='nom_ins_udi',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Nom INS UDI'),
        ),
    ]
