# Generated by Django 5.2.6 on 2025-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0004_alter_udi_nom_ins_udi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udi',
            name='nom_quartier',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nom du quartier desservi'),
        ),
    ]
