# Generated by Django 5.2.6 on 2025-10-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0005_alter_udi_nom_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udi',
            name='communes',
            field=models.ManyToManyField(related_name='udis', to='observatoire.commune', verbose_name='Communes desservies'),
        ),
    ]
