# Generated by Django 5.2.6 on 2025-10-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0006_alter_udi_communes'),
    ]

    operations = [
    ]
