# Generated by Django 5.2.6 on 2025-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0007_create_udi_communes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['-order', 'name']},
        ),
        migrations.AddField(
            model_name='layer',
            name='order',
            field=models.IntegerField(default=0, help_text='Plus la valeur est élevée, plus la couche est au-dessus', verbose_name="Ordre d'affichage"),
        ),
    ]
