# Generated by Django 5.2.6 on 2025-11-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0009_captage_code_masse_eau_souterraine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uge',
            name='feature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uge', to='observatoire.feature', verbose_name='Entité géographique associée'),
        ),
    ]
